import { Action, useRegisterActions } from 'kbar'
import { useRouter } from 'next/router'
import {
  RiGithubFill,
  RiSnapchatFill,
  RiHomeFill,
  RiGlobeFill,
  RiQuestionAnswerFill,
  RiMacbookFill,
  RiLineChartFill,
  RiRssFill,
  RiMailSendFill,
  RiLinkedinFill,
  RiDribbbleFill,
  RiYoutubeFill,
  RiTelegramFill,
  RiBehanceFill,
} from 'react-icons/ri'

const actions: Action[] = [
  {
    id: 'home',
    name: 'Home',
    shortcut: ['h'],
    keywords: 'back',
    icon: RiHomeFill,
    perform: () => window.open('/', '_self'),
    section: 'Navigation',
  },
  {
    id: 'about',
    name: 'About',
    icon: RiGlobeFill,
    shortcut: ['a', 'b'],
    keywords: 'bio',
    section: 'Navigation',
    perform: () => window.open('/abt', '_self'),
  },
  {
    id: 'ama',
    name: 'Ask Me Anything',
    icon: RiQuestionAnswerFill,
    shortcut: ['a'],
    keywords: 'qna ask',
    section: 'Navigation',
    perform: () => window.open('/ama', '_self'),
  },
  {
    id: 'uses',
    name: 'Uses',
    icon: RiMacbookFill,
    shortcut: ['u'],
    keywords: 'tech gear',
    section: 'Navigation',
    subtitle: 'All my gear',
    perform: () => window.open('/uses', '_self'),
  },
  {
    id: 'stats',
    name: 'Stats',
    icon: RiLineChartFill,
    shortcut: ['s'],
    keywords: 'dashboard',
    section: 'Navigation',
    subtitle: 'Bunch of cool and interesting statistics about me',
    perform: () => window.open('/stats', '_self'),
  },
  {
    id: 'rss',
    name: 'RSS',
    shortcut: ['r', 's'],
    icon: RiRssFill,
    keywords: 'feed',
    section: 'Navigation',
    perform: () => window.open('/rss.xml', '_self'),
  },
  {
    id: 'email',
    name: 'Contact',
    shortcut: ['c'],
    keywords: 'email hello',
    section: 'Navigation',
    perform: () => window.open('mailto:hi.harsh@proton.me', '_blank'),
  },
  {
    id: 'twitter',
    name: 'Twitter',
    icon: RiMailSendFill,
    shortcut: ['t', 'w'],
    keywords: 'social contact dm tweets',
    section: 'Socials',
    subtitle: 'Just a bunch of random stuff, and announcements',
    perform: () => window.open('https://twitter.com/harshhhdev', '_blank'),
  },
  {
    id: 'github',
    name: 'GitHub',
    icon: RiGithubFill,
    shortcut: ['g', 'h'],
    keywords: 'social source gh',
    section: 'Socials',
    subtitle: 'View my open-source projects',
    perform: () => window.open('https://github.com/harshhhdev', '_blank'),
  },
  {
    id: 'linkedin',
    name: 'Linkedin',
    icon: RiLinkedinFill,
    shortcut: ['l', 'n'],
    keywords: 'resume work hire social contact dm email',
    subtitle: 'Resume, and more important information regarding me',
    section: 'Socials',
    perform: () => window.open('https://linkedin.com/in/harshhhdev', '_blank'),
  },
  {
    id: 'dribbble',
    name: 'Dribbble',
    icon: RiDribbbleFill,
    shortcut: ['d', 'r'],
    keywords: 'design social',
    subtitle: 'Simple and sweet design projects',
    section: 'Socials',
    perform: () => window.open('https://dribbble.com/harshhhdev', '_blank'),
  },
  {
    id: 'yt',
    name: 'YouTube',
    icon: RiYoutubeFill,
    shortcut: ['y', 't'],
    keywords: 'yt social channel videos',
    section: 'Socials',
    subtitle: "I don't post often, mainly just for showcasing",
    perform: () =>
      window.open(
        'https://www.youtube.com/channel/UC6ix6gYRC62pM0sMRYKPKUQ',
        '_blank'
      ),
  },
  {
    id: 'telegram',
    name: 'Telegram',
    icon: RiTelegramFill,
    shortcut: ['t', 'g'],
    keywords: 'social contact dm message',
    section: 'Socials',
    perform: () => window.open('https://t.me/harshhhdev', '_blank'),
  },
  {
    id: 'behance',
    name: 'Behance',
    icon: RiBehanceFill,
    shortcut: ['b', 'h'],
    keywords: 'social contact dm message',
    subtitle:
      'Generally for larger design projects, such as entire app redesigns',
    section: 'Socials',
    perform: () => window.open('https://behance.net/harshhhdev', '_blank'),
  },
  {
    id: 'snapchat',
    name: 'Snapchat',
    icon: RiSnapchatFill,
    shortcut: ['s', 'c'],
    keywords: 'social contact dm message',
    section: 'Socials',
    perform: () =>
      window.open('https://www.snapchat.com/add/harshhhhsingh', '_blank'),
  },
]

export default actions
