import { globalCss } from './theme.config'

const global = globalCss({
  ':root': { colorScheme: 'dark' },
  '*': { boxSizing: 'border-box', padding: 0, margin: 0 },
  '*,::before,::after': { borderWidth: 0, borderStyle: 'solid' },
  'ol, ul': { listStyle: 'none', margin: 0, padding: 0 },
  'img, svg, video, canvas, audio, iframe, embed, object': {
    display: 'block',
    verticalAlign: 'middle',
    userSelect: 'none',
  },
  'html, body': {
    background: '$grey900',
    scrollBehavior: 'smooth',
    fontFamily: '$sans !important',
  },
  h1: { fontSize: '$2xl', color: '$grey0' },
  h3: { color: '$grey0', fontWeight: 'bold', fontSize: '$lg' },
  '::-moz-selection': { color: '#e5e5e5', background: '#3c3c3c' },
  '::selection': { color: '#e5e5e5', background: '#3c3c3c' },
  button: {
    cursor: 'pointer',
    userSelect: 'none',
    background: 'none',
    fontSize: '$base',
  },
  'button, input, textarea': { fontFamily: '$sans' },
  a: {
    color: '$grey0',
    transitionProperty:
      'color, background-color, border-color, text-decoration-color, fill, stroke',
    transitionTimingFunction: 'cubic-bezier(0.4, 0, 0.2, 1)',
    transitionDuration: '150ms',
    textDecoration: 'none',
  },
  'a:hover': { color: '$grey0' },
  'p > a, li > a': {
    textDecoration: 'underline',
    textUnderlineOffset: 4,
    textDecorationColor: '$grey700',
    background:
      'linear-gradient(0deg, #ffffff20, #ffffff20) no-repeat right bottom / 0 100%',
    transition: 'background-size 0.2s',
  },
  'li > a:where(:hover, :focus-visible), p > a:where(:hover, :focus-visible)': {
    backgroundSize: '100% 100%',
    backgroundPositionX: 'left',
  },
  'p, li': { color: '$grey600', fontSize: '$base' },
  li: { marginLeft: 40, listStyleType: 'disc', margin: '8px 0' },
  i: { color: '$grey0' },
  '.blog > .header': { textDecorationLine: 'none' },
  '.blog > p': { fontSize: '$base', margin: '16px 0', lineHeight: '28px' },
  '.blog > img': { borderRadius: 4, margin: '96px 0', width: '100%' },
  '.rehype-code-title': {
    padding: '12px 20px',
    fontSize: '$sm',
    fontFamily: '$mono !important',
    borderWidth: 1,
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    color: '$grey200',
    borderColor: '$grey700',
    backgroundColor: '$grey80',
    marginTop: 20,
  },
  "code[class*='language-'], pre[class*='language-']": { color: '$grey600' },
  'code,kbd,samp,pre': { fontFamily: '$mono !important' },
  '.blog pre': {
    borderWidth: 1,
    borderColor: '$grey700',
    backgroundColor: '$grey900',
    padding: '12px 20px',
    borderBottomRightRadius: 8,
    borderBottomLeftRadius: 8,
    overflowX: 'auto',
  },
  '.blog code': {
    color: '$grey200',
    padding: '2px 4px',
    borderWidth: 1,
    borderColor: '$grey700',
    borderRadius: 8,
    backgroundColor: '$grey900',
    overflow: 'scroll',
    fontSize: '$sm',
  },
  '.blog pre code': { color: '$grey200', padding: 0, border: 'initial' },
  '.blog thead': { color: '$grey0', fontSize: '$base', textAlign: 'left' },
  '.blog td, th': { color: '$grey0', padding: '20px 28px' },
  '.blog td': { color: '$grey600' },
  '.blog p > code': {
    fontSize: '$base',
    color: '$grey400',
    borderRadius: 4,
  },
  '.blog blockquote': {
    fontStyle: 'italic',
    borderLeftWidth: 4,
    padding: 20,
    borderColor: '$grey700',
    background: 'rgb(46 46 46 / 0.5)',
    borderRadius: 4,
    margin: '20px 0',
  },
  '@media (min-width: 640px)': { img: { height: 'fit-content' } },
  '@media (min-width: 1024px)': { '.blog img': { transform: 'scale(1.1)' } },
})

export default global
